#!/bin/sh
#
# Script to move TV Episodes from Sabnzdb Download Folder to destination
#
# English version

# Variablendeklaration
BaseDir=/media/d3c21c66-af4b-41d4-b098-462e83fa641d/Serien/
ShortBD=/ln/target/Englisch
DownloadDir=/opt/SABnzbd/Downloads/complete/
Serie="{n.replaceAll(/[!?.]+\$/).replaceAll(/[\`´‘’ʻ]/, \"'\").replace(':',' -')}"
Titel="{t.replaceAll(/[!?.]+\$/).replaceAll(/[\`´‘’ʻ]/, \"'\")}"

moveen(){
        filebot -rename "$DownloadDir" --db thetvdb --format "$ShortBD/$Serie/Staffel {s} EN {vf}/$Serie - {s00e00} - $Titel" -non-strict -r
}

moveen

exit 0
